Rewrite the task with Kotlin
dkukishev/techeryAutomation pull request #1
Opened 2022-08-07 19:29 UTC by dkukishev

Pls check!
I'll really appreciate your comment and improvements
Pls check the Test.kt file

2022-08-08 14:55 UTC, Dimdron requested changes

2022-08-08 14:55 UTC, Dimdron commented on src/Test.kt
> +    for (i in array[0]..array.size){
а тут точно правильно?)

2022-08-08 14:56 UTC, Dimdron commented on src/Test.kt
> +    for (i in array[0]..array.size){
какой тут рендж будет?

2022-08-08 16:05 UTC, dkukishev commented on src/Test.kt
> +    for (i in array[0]..array.size){
Сумму считает правильно)
рендж получается с первого елемента аррея и до последнего. Оно как раз доходит до 10, хотя по индексам их 9. И не учитівает 10й, но правильно учитівает 9й

2022-08-08 16:37 UTC, Dimdron commented on src/Test.kt
> +    for (i in array[0]..array.size){
понял, тут переменная 'i' не используется) 
переделывай, чтобы она использовалась вместо 'cou'

2022-08-08 17:28 UTC, dkukishev commented on src/Test.kt
> +    for (i in array[0]..array.size){
Поправил )

2022-08-09 11:22 UTC, Dimdron commented on src/Test.kt
> +    var count: Double = array.size.toDouble()
а зачем тут Double?

2022-08-10 07:42 UTC, dkukishev commented on src/Test.kt
> +    var count: Double = array.size.toDouble()
потому что авередж может біть не целім. Например в моем случаи получается 5.5

2022-08-18 18:47 UTC, Dimdron approved these changes

2022-08-20 10:03 UTC, Dimdron commented
Other PR contains these commits.

2022-08-20 10:03 UTC, closed without merging